11:25:40 - INFO: Starting epoch 0:
  0%|                                                                                                                                                                                                                             | 0/239282 [00:00<?, ?it/s]/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/nn/modules/loss.py:128: UserWarning: Using a target size (torch.Size([1, 9, 1089])) that is different to the input size (torch.Size([1, 1089, 64])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
current_pressure shape: torch.Size([1, 99, 99])
current_patches shape: torch.Size([1, 1089, 64])
next_pressures shape: torch.Size([1, 99, 99])
next_patches shape: torch.Size([1, 9, 1089])
charge_data shape: torch.Size([1, 7])
wall_locations shape: torch.Size([1, 3, 6])
current_time shape: torch.Size([1, 1])
next_time shape: torch.Size([1, 1])
outputs shape: torch.Size([1, 1094, 1089])
predicted_patches shape: torch.Size([1, 9, 1089])
  return F.l1_loss(input, target, reduction=self.reduction)
  0%|                                                                                                                                                                                                                             | 0/239282 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/reid/projects/blast_waves/blastformer/lucid_train.py", line 159, in <module>
    launch()
  File "/home/reid/projects/blast_waves/blastformer/lucid_train.py", line 155, in launch
    train(args)
  File "/home/reid/projects/blast_waves/blastformer/lucid_train.py", line 89, in train
    loss = l1(current_patches, predicted_patches)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/nn/modules/loss.py", line 128, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/nn/functional.py", line 3753, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reid/anaconda3/envs/blast_waves/lib/python3.12/site-packages/torch/functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (64) must match the size of tensor b (1089) at non-singleton dimension 2
